# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Troxel Custom Carpentry
email: oxtrox@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Custom carpentry in Ohio's Middletown–Kettering–Oxford area.
street_address_1: "7448 Michael Road"
street_address_2: "Middletown, OH 45042"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.troxelcc.com" # the base hostname & protocol for your site
facebook_url: "https://www.facebook.com/pages/Troxel-Custom-Carpentry-Inc/579632255416602"
github_username: troxelcc

# Build settings
markdown: kramdown
